//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo7
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_1
    {
        public int OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public string ProductArticleNumber { get; set; }
        public string ProductName { get; set; }
        public decimal ProductCost { get; set; }
        public int ProductDiscountMax { get; set; }
        public byte ProductDiscountAmount { get; set; }
        public Nullable<int> CountProduct { get; set; }
        public string UserSurname { get; set; }
    }
}
